name: Deploy Main

on:
  create:
    tags:
      - v*

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.2' # The Go version to download (if necessary) and use.
        
    - name: Build Binaries
      run: go run github.com/mitchellh/gox -osarch="!darwin/386" -os="windows linux darwin" -arch="386 amd64"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          turbine_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          